[workspace]
resolver="2"
members=["crates/keygate"]

[workspace.package]
edition="2021"
license="Apache-2.0"
authors=["Henry Gressmann <mail@henrygressmann.de>"]
repository="https://github.com/explodingcamera/keygate"
