[package]
edition = "2021"
name = "keysignal-core"
version = "0.1.0"

[lib]
path = "lib.rs"

[dependencies]
dashmap = "5"
jsonwebtoken = {version = "8", default-features = false}
nanoid = "0.4.0"
oauth2 = {version = "4", optional = true, default-features = false, features = ["rustls-tls"]}
rkyv = {version = "0.7", features = ["strict"]}
rocksdb = {default-features = false, version = "0.19.0", features = ["lz4"]}
rust-argon2 = "1.0"

[features]
default = ["oauth2"]
oauth2 = ["dep:oauth2"]
