[package]
edition = "2021"
name = "proto"
private = true
version = "0.1.0"

[lib]
path = "lib.rs"

[dependencies]
bytes = "1.1"
prost = "0.11"

[build-dependencies]
tonic-build = "0.8"

[features]
client = []
default = []
server = []
