[package]
edition = "2021"
name = "keygate-core"
version = "0.1.0"

[lib]
path = "lib.rs"

[dependencies]

# crypto and hashing
argon2 = "0.4"
keygate-jwt = {version = "1.2", features = ["eddsa"]}
nanoid = "0.4.0"
rand_core = {version = "0.6", features = ["std"]}
sha1 = "0.10"

# serialization/encoding
hex = "0.4.3"
regex = "1.5"
rmp-serde = "1.1"
serde = {version = "1.0", features = ["derive"]}

# datastructures
arc-swap = "1.6.0"
chrono = {version = "0.4", features = ["serde"]}
dashmap = "5"

# macros
async-trait = "0.1"
thiserror = "1"

# redis
redis = {version = "0.22", default-features = false, optional = true, features = ["aio", "connection-manager"]}

# sql
entity = {optional = true, path = "storage/sql/entity"}
migration = {optional = true, path = "storage/sql/migration"}
sea-orm = {version = "0.11", optional = true, features = ["macros"]}

# async runtimes
async-std = {version = "1", optional = true}
tokio = {version = "1", optional = true, default-features = false, features = ["macros"]}

# misc
extrasafe = "0.1.2"
reqwest = {version = "0.11", default-features = false, features = ["rustls-tls"]}

[dev-dependencies]

[features]
default = ["backend-redis", "backend-sqlite", "runtime-tokio"]

backend-redis = ["redis"]

backend-mysql = ["sql", "sea-orm/sqlx-mysql"]
backend-postgres = ["sql", "sea-orm/sqlx-postgres"]
backend-sqlite = ["sql", "sea-orm/sqlx-sqlite"]
sql = ["sea-orm", "entity", "migration"]

runtime-async-std = ["async-std", "sea-orm?/runtime-async-std-rustls"]
runtime-tokio = ["tokio", "sea-orm?/runtime-tokio-rustls", "redis?/tokio-comp"]
