[package]
edition = "2021"
name = "keygate-core"
version = "0.1.0"

[lib]
path = "lib.rs"

[dependencies]
arc-swap = "1.6"
argon2 = "0.5"
async-trait = "0.1"
chrono = {version = "0.4"}
keygate-jwt = {version = "1.2", features = ["eddsa"]}
keygate-utils = {path = "../utils"}
rusty_paseto = "0.5"
serde = {version = "1.0", features = ["derive"]}
thiserror = "1.0"
tokio = {version = "1", default-features = false, features = ["macros"]}

prisma = {path = "./prisma"}

# proto
proto = {path = "../proto"}
tonic = {version = "0.9", features = ["tls"]}

[features]
default = []
