[package]
edition = "2021"
name = "keygate-server"
publish = false
version = "0.1.0"

[lib]
path = "lib.rs"

[[bin]]
name = "keygate"
path = "bin.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6"
keygate-core = {path = "../core"}
thiserror = "1"
tokio = {version = "1", features = ["rt-multi-thread", "macros", "sync", "time"]}

# gRPC dependencies
proto = {path = "../proto", features = ["server"]}
tonic = {version = "0.9", features = ["tls"]}

# REST dependencies
poem = "1.3"
poem-openapi = "2.0"
