[package]
edition = "2021"
name = "keygate-server"
publish = false
version = "0.1.0"

[lib]
path = "lib.rs"

[[bin]]
name = "keygate"
path = "bin.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
extrasafe = "0.1.2"
eyre = "0.6"
keygate-core = {path = "../core"}
thiserror = "1"
tokio = {version = "1"}
